/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    cities: City;
    barbers: Barber;
    services: Service;
    appointments: Appointment;
    reviews: Review;
    availabilityExceptions: AvailabilityException;
    portfolio: Portfolio;
    conversations: Conversation;
    messages: Message;
    notifications: Notification;
    subscriptionPlans: SubscriptionPlan;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    barbers: BarbersSelect<false> | BarbersSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    appointments: AppointmentsSelect<false> | AppointmentsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    availabilityExceptions: AvailabilityExceptionsSelect<false> | AvailabilityExceptionsSelect<true>;
    portfolio: PortfolioSelect<false> | PortfolioSelect<true>;
    conversations: ConversationsSelect<false> | ConversationsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    subscriptionPlans: SubscriptionPlansSelect<false> | SubscriptionPlansSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
    home: Home;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  role: 'customer' | 'barber' | 'admin';
  phone?: string | null;
  avatar?: (string | null) | Media;
  /**
   * کاربر تأیید شده است
   */
  isVerified?: boolean | null;
  activeBarber?: (string | null) | Barber;
  createdAt: string;
  updatedAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "barbers".
 */
export interface Barber {
  id: string;
  user?: (string | null) | User;
  shopName: string;
  /**
   * شناسه یکتا برای آدرس پروفایل
   */
  shopSlug?: string | null;
  city: string | City;
  address?: string | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  location?: [number, number] | null;
  about?: string | null;
  phone?: string | null;
  avatar?: (string | null) | Media;
  cover?: (string | null) | Media;
  experienceYears?: number | null;
  isVerified?: boolean | null;
  isActive?: boolean | null;
  /**
   * نمایش در بخش «آرایشگران ویژه» صفحه اصلی
   */
  isFeatured?: boolean | null;
  rating?: number | null;
  reviewCount?: number | null;
  /**
   * ساعات کاری تکراری هفتگی. هر روز شامل جهت ساعات کاری است.
   */
  workingHours?:
    | {
        day: 'saturday' | 'sunday' | 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday';
        enabled?: boolean | null;
        slots?:
          | {
              start: string;
              end: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: string;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  province:
    | 'azarbaijan-sharghi'
    | 'azarbaijan-gharbi'
    | 'ardabil'
    | 'isfahan'
    | 'alborz'
    | 'ilam'
    | 'bushehr'
    | 'tehran'
    | 'chaharmahal-bakhtiari'
    | 'khorasan-jonubi'
    | 'khorasan-razavi'
    | 'khorasan-shomali'
    | 'khuzestan'
    | 'zanjan'
    | 'semnan'
    | 'sistan-baluchestan'
    | 'fars'
    | 'qazvin'
    | 'qom'
    | 'kurdistan'
    | 'kerman'
    | 'kermanshah'
    | 'kohgiluyeh-boyerahmad'
    | 'golestan'
    | 'gilan'
    | 'lorestan'
    | 'mazandaran'
    | 'markazi'
    | 'hormozgan'
    | 'hamadan'
    | 'yazd';
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  name: string;
  description?: string | null;
  barber?: (string | null) | Barber;
  price: number;
  /**
   * مدت زمان به دقیقه
   */
  duration: number;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments".
 */
export interface Appointment {
  id: string;
  barber: string | Barber;
  customer: string | User;
  service?: (string | null) | Service;
  /**
   * عکس فوری از نام خدمت در زمان رزرو
   */
  serviceName?: string | null;
  /**
   * عکس فوری از قیمت در زمان رزرو
   */
  price?: number | null;
  /**
   * مدت به دقیقه
   */
  duration?: number | null;
  date: string;
  /**
   * ساعت شروع، e.g. 18:30
   */
  startTime: string;
  endTime?: string | null;
  status: 'pending' | 'confirmed' | 'completed' | 'cancelled';
  note?: string | null;
  cancelReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: string;
  barber: string | Barber;
  customer: string | User;
  appointment?: (string | null) | Appointment;
  rating: number;
  comment?: string | null;
  status: 'pending' | 'active' | 'rejected';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "availabilityExceptions".
 */
export interface AvailabilityException {
  id: string;
  barber: string | Barber;
  label?: string | null;
  date: string;
  allDay?: boolean | null;
  slots?:
    | {
        start: string;
        end: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio".
 */
export interface Portfolio {
  id: string;
  title: string;
  barber: string | Barber;
  image: string | Media;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations".
 */
export interface Conversation {
  id: string;
  participants: (string | User)[];
  barber?: (string | null) | Barber;
  lastMessage?: string | null;
  lastMessageAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: string;
  conversation: string | Conversation;
  sender: string | User;
  content: string;
  readAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: string;
  user: string | User;
  type: 'appointment' | 'message' | 'system' | 'subscription';
  title?: string | null;
  body?: string | null;
  readAt?: string | null;
  /**
   * داده اضافی ساختاریافته برای هدایت کاربر
   */
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptionPlans".
 */
export interface SubscriptionPlan {
  id: string;
  name: string;
  description?: string | null;
  price: number;
  durationMonths: number;
  features?:
    | {
        feature?: string | null;
        id?: string | null;
      }[]
    | null;
  isActive?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'cities';
        value: string | City;
      } | null)
    | ({
        relationTo: 'barbers';
        value: string | Barber;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'appointments';
        value: string | Appointment;
      } | null)
    | ({
        relationTo: 'reviews';
        value: string | Review;
      } | null)
    | ({
        relationTo: 'availabilityExceptions';
        value: string | AvailabilityException;
      } | null)
    | ({
        relationTo: 'portfolio';
        value: string | Portfolio;
      } | null)
    | ({
        relationTo: 'conversations';
        value: string | Conversation;
      } | null)
    | ({
        relationTo: 'messages';
        value: string | Message;
      } | null)
    | ({
        relationTo: 'notifications';
        value: string | Notification;
      } | null)
    | ({
        relationTo: 'subscriptionPlans';
        value: string | SubscriptionPlan;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  phone?: T;
  avatar?: T;
  isVerified?: T;
  activeBarber?: T;
  createdAt?: T;
  updatedAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  province?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "barbers_select".
 */
export interface BarbersSelect<T extends boolean = true> {
  user?: T;
  shopName?: T;
  shopSlug?: T;
  city?: T;
  address?: T;
  location?: T;
  about?: T;
  phone?: T;
  avatar?: T;
  cover?: T;
  experienceYears?: T;
  isVerified?: T;
  isActive?: T;
  isFeatured?: T;
  rating?: T;
  reviewCount?: T;
  workingHours?:
    | T
    | {
        day?: T;
        enabled?: T;
        slots?:
          | T
          | {
              start?: T;
              end?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  barber?: T;
  price?: T;
  duration?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments_select".
 */
export interface AppointmentsSelect<T extends boolean = true> {
  barber?: T;
  customer?: T;
  service?: T;
  serviceName?: T;
  price?: T;
  duration?: T;
  date?: T;
  startTime?: T;
  endTime?: T;
  status?: T;
  note?: T;
  cancelReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  barber?: T;
  customer?: T;
  appointment?: T;
  rating?: T;
  comment?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "availabilityExceptions_select".
 */
export interface AvailabilityExceptionsSelect<T extends boolean = true> {
  barber?: T;
  label?: T;
  date?: T;
  allDay?: T;
  slots?:
    | T
    | {
        start?: T;
        end?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio_select".
 */
export interface PortfolioSelect<T extends boolean = true> {
  title?: T;
  barber?: T;
  image?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations_select".
 */
export interface ConversationsSelect<T extends boolean = true> {
  participants?: T;
  barber?: T;
  lastMessage?: T;
  lastMessageAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  conversation?: T;
  sender?: T;
  content?: T;
  readAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  user?: T;
  type?: T;
  title?: T;
  body?: T;
  readAt?: T;
  data?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptionPlans_select".
 */
export interface SubscriptionPlansSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  price?: T;
  durationMonths?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: string;
  general?: {
    siteName?: string | null;
    /**
     * لوگوی برند (در هدر و فوتر نمایش داده می‌شود)
     */
    logo?: (string | null) | Media;
    supportPhone?: string | null;
    supportEmail?: string | null;
    timezone?: string | null;
  };
  booking?: {
    /**
     * گام زمانی اسلات‌ها (دقیقه)
     */
    slotStepMinutes?: number | null;
    /**
     * حداقل زمان قبل از شروع رزرو برای لغو بدون جریمه
     */
    cancellationWindowMinutes?: number | null;
    /**
     * حداکثر فاصله روز برای رزرو
     */
    maxBookingHorizonDays?: number | null;
    defaultStatus?: ('pending' | 'confirmed') | null;
  };
  navigation?: {
    /**
     * لینک‌های ناوبری هدر (خانه، آرایشگرها و...)
     */
    links?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  auth?: {
    registrationEnabled?: boolean | null;
    otpEnabled?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: string;
  hero?: {
    title?: string | null;
    subtitle?: string | null;
    image?: (string | null) | Media;
  };
  stats?: {
    barbersCount?: number | null;
    appointmentsCount?: number | null;
    citiesCount?: number | null;
    customersCount?: number | null;
  };
  promo?: {
    title?: string | null;
    body?: string | null;
    image?: (string | null) | Media;
    link?: string | null;
  };
  /**
   * خدمات منتخب جهت نمایش در بخش محبوب
   */
  popularServices?: (string | Service)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  general?:
    | T
    | {
        siteName?: T;
        logo?: T;
        supportPhone?: T;
        supportEmail?: T;
        timezone?: T;
      };
  booking?:
    | T
    | {
        slotStepMinutes?: T;
        cancellationWindowMinutes?: T;
        maxBookingHorizonDays?: T;
        defaultStatus?: T;
      };
  navigation?:
    | T
    | {
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
      };
  auth?:
    | T
    | {
        registrationEnabled?: T;
        otpEnabled?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        image?: T;
      };
  stats?:
    | T
    | {
        barbersCount?: T;
        appointmentsCount?: T;
        citiesCount?: T;
        customersCount?: T;
      };
  promo?:
    | T
    | {
        title?: T;
        body?: T;
        image?: T;
        link?: T;
      };
  popularServices?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}