/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    otps: Otp;
    media: Media;
    cities: City;
    barbers: Barber;
    services: Service;
    appointments: Appointment;
    'barber-requests': BarberRequest;
    comments: Comment;
    conversations: Conversation;
    messages: Message;
    notifications: Notification;
    subscriptionPlans: SubscriptionPlan;
    subscriptions: Subscription;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    barbers: {
      appointments: 'appointments';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    otps: OtpsSelect<false> | OtpsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    barbers: BarbersSelect<false> | BarbersSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    appointments: AppointmentsSelect<false> | AppointmentsSelect<true>;
    'barber-requests': BarberRequestsSelect<false> | BarberRequestsSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    conversations: ConversationsSelect<false> | ConversationsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    subscriptionPlans: SubscriptionPlansSelect<false> | SubscriptionPlansSelect<true>;
    subscriptions: SubscriptionsSelect<false> | SubscriptionsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
    home: Home;
    footer: Footer;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    username: string;
  };
  login: {
    password: string;
    username: string;
  };
  registerFirstUser: {
    password: string;
    username: string;
  };
  unlock: {
    username: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * برای فعال‌شدن حساب، نام خود را در پروفایل کامل کنید.
   */
  name?: string | null;
  role: 'customer' | 'barber' | 'admin';
  avatar?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  email?: string | null;
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "otps".
 */
export interface Otp {
  id: string;
  phone: string;
  role: 'customer' | 'barber';
  code: string;
  expiresAt: string;
  used?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: string;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  province:
    | 'azarbaijan-sharghi'
    | 'azarbaijan-gharbi'
    | 'ardabil'
    | 'isfahan'
    | 'alborz'
    | 'ilam'
    | 'bushehr'
    | 'tehran'
    | 'chaharmahal-bakhtiari'
    | 'khorasan-jonubi'
    | 'khorasan-razavi'
    | 'khorasan-shomali'
    | 'khuzestan'
    | 'zanjan'
    | 'semnan'
    | 'sistan-baluchestan'
    | 'fars'
    | 'qazvin'
    | 'qom'
    | 'kurdistan'
    | 'kerman'
    | 'kermanshah'
    | 'kohgiluyeh-boyerahmad'
    | 'golestan'
    | 'gilan'
    | 'lorestan'
    | 'mazandaran'
    | 'markazi'
    | 'hormozgan'
    | 'hamadan'
    | 'yazd';
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "barbers".
 */
export interface Barber {
  id: string;
  user?: (string | null) | User;
  shopName: string;
  city: string | City;
  address?: string | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  location?: [number, number] | null;
  about?: string | null;
  phone?: string | null;
  cover?: (string | null) | Media;
  /**
   * تصاویر گالری صفحه پروفایل آرایشگر
   */
  gallery?: (string | Media)[] | null;
  experienceYears?: number | null;
  rating?: number | null;
  reviewCount?: number | null;
  /**
   * وقتی نام، نام آرایشگاه و شهر کامل باشد، این آرایشگاه به‌صورت خودکار فعال می‌شود.
   */
  isPublic?: boolean | null;
  /**
   * وقت‌هایی که این آرایشگر در یک بازه زمانی مشخص ارائه می‌دهد.
   */
  appointments?: {
    docs?: (string | Appointment)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * خدماتی که این آرایشگر ارائه می‌دهد (از کاتالوگ ادمین انتخاب می‌شود).
   */
  services?: (string | Service)[] | null;
  /**
   * کاربرانی که مشتری این آرایشگر هستند (به‌صورت خودکار هنگام رزرو اضافه می‌شوند).
   */
  customers?: (string | User)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments".
 */
export interface Appointment {
  id: string;
  barber?: (string | null) | Barber;
  service?: (string | null) | Service;
  fromDate: string;
  toDate: string;
  customer?: (string | null) | User;
  /**
   * پیامی که مشتری هنگام رزرو نوشته است (اختیاری).
   */
  customerMessage?: string | null;
  status: 'available' | 'reserved' | 'cancelled';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  name: string;
  description?: string | null;
  /**
   * تصویر / آیکون خدمت
   */
  icon?: (string | null) | Media;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "barber-requests".
 */
export interface BarberRequest {
  id: string;
  barber: string | Barber;
  customer: string | User;
  status: 'pending' | 'approved' | 'rejected';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: string;
  barber: string | Barber;
  author: string | User;
  rating: number;
  content: string;
  status: 'pending' | 'active' | 'rejected';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations".
 */
export interface Conversation {
  id: string;
  participants: (string | User)[];
  barber?: (string | null) | Barber;
  lastMessage?: string | null;
  lastMessageAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: string;
  conversation: string | Conversation;
  sender: string | User;
  content: string;
  readAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: string;
  user: string | User;
  type: 'appointment' | 'message' | 'system' | 'subscription';
  title?: string | null;
  body?: string | null;
  readAt?: string | null;
  /**
   * داده اضافی ساختاریافته برای هدایت کاربر
   */
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptionPlans".
 */
export interface SubscriptionPlan {
  id: string;
  name: string;
  description?: string | null;
  price: number;
  durationMonths: number;
  features?:
    | {
        feature?: string | null;
        id?: string | null;
      }[]
    | null;
  isActive?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: string;
  barber: string | Barber;
  plan: string | SubscriptionPlan;
  status: 'active' | 'cancelled';
  startsAt: string;
  expiresAt: string;
  amount?: number | null;
  /**
   * در اتصال درگاه پرداخت، شناسه تراکنش اینجا ذخیره می‌شود
   */
  paymentRef?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  status: 'published' | 'draft';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'otps';
        value: string | Otp;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'cities';
        value: string | City;
      } | null)
    | ({
        relationTo: 'barbers';
        value: string | Barber;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'appointments';
        value: string | Appointment;
      } | null)
    | ({
        relationTo: 'barber-requests';
        value: string | BarberRequest;
      } | null)
    | ({
        relationTo: 'comments';
        value: string | Comment;
      } | null)
    | ({
        relationTo: 'conversations';
        value: string | Conversation;
      } | null)
    | ({
        relationTo: 'messages';
        value: string | Message;
      } | null)
    | ({
        relationTo: 'notifications';
        value: string | Notification;
      } | null)
    | ({
        relationTo: 'subscriptionPlans';
        value: string | SubscriptionPlan;
      } | null)
    | ({
        relationTo: 'subscriptions';
        value: string | Subscription;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "otps_select".
 */
export interface OtpsSelect<T extends boolean = true> {
  phone?: T;
  role?: T;
  code?: T;
  expiresAt?: T;
  used?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  province?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "barbers_select".
 */
export interface BarbersSelect<T extends boolean = true> {
  user?: T;
  shopName?: T;
  city?: T;
  address?: T;
  location?: T;
  about?: T;
  phone?: T;
  cover?: T;
  gallery?: T;
  experienceYears?: T;
  rating?: T;
  reviewCount?: T;
  isPublic?: T;
  appointments?: T;
  services?: T;
  customers?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  icon?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments_select".
 */
export interface AppointmentsSelect<T extends boolean = true> {
  barber?: T;
  service?: T;
  fromDate?: T;
  toDate?: T;
  customer?: T;
  customerMessage?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "barber-requests_select".
 */
export interface BarberRequestsSelect<T extends boolean = true> {
  barber?: T;
  customer?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  barber?: T;
  author?: T;
  rating?: T;
  content?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations_select".
 */
export interface ConversationsSelect<T extends boolean = true> {
  participants?: T;
  barber?: T;
  lastMessage?: T;
  lastMessageAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  conversation?: T;
  sender?: T;
  content?: T;
  readAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  user?: T;
  type?: T;
  title?: T;
  body?: T;
  readAt?: T;
  data?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptionPlans_select".
 */
export interface SubscriptionPlansSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  price?: T;
  durationMonths?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions_select".
 */
export interface SubscriptionsSelect<T extends boolean = true> {
  barber?: T;
  plan?: T;
  status?: T;
  startsAt?: T;
  expiresAt?: T;
  amount?: T;
  paymentRef?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  content?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: string;
  general?: {
    siteName?: string | null;
    /**
     * لوگوی برند (در هدر و فوتر نمایش داده می‌شود)
     */
    logo?: (string | null) | Media;
    supportPhone?: string | null;
    supportEmail?: string | null;
    timezone?: string | null;
  };
  booking?: {
    /**
     * گام زمانی اسلات‌ها (دقیقه)
     */
    slotStepMinutes?: number | null;
    /**
     * حداقل زمان قبل از شروع رزرو برای لغو بدون جریمه
     */
    cancellationWindowMinutes?: number | null;
    /**
     * حداکثر فاصله روز برای رزرو
     */
    maxBookingHorizonDays?: number | null;
    defaultStatus?: ('pending' | 'confirmed') | null;
  };
  navigation?: {
    /**
     * لینک‌های ناوبری هدر (خانه، آرایشگرها و...)
     */
    links?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  monetization?: {
    /**
     * مشتریان همیشه رایگان‌اند؛ با فعال بودن این گزینه، آرایشگرها بعد از پایان دوره آزمایشی باید اشتراک فعال داشته باشند تا نوبت بپذیرند.
     */
    enforceSubscription?: boolean | null;
    /**
     * از لحظه ساخت پروفایل آرایشگر محاسبه می‌شود
     */
    trialDays?: number | null;
  };
  auth?: {
    registrationEnabled?: boolean | null;
    otpEnabled?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: string;
  hero?: {
    title?: string | null;
    subtitle?: string | null;
    image?: (string | null) | Media;
  };
  stats?: {
    barbersCount?: number | null;
    appointmentsCount?: number | null;
    citiesCount?: number | null;
    customersCount?: number | null;
  };
  /**
   * دلایلی که چرا مشتریان باید از ما استفاده کنند.
   */
  whyUs?:
    | {
        title: string;
        icon?: (string | null) | Media;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * خدمات منتخب جهت نمایش در بخش محبوب
   */
  popularServices?: (string | Service)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  brand?: {
    /**
     * توضیح کوتاهی که زیر نام سایت در فوتر نمایش داده می‌شود.
     */
    aboutText?: string | null;
  };
  /**
   * هر ستون یک عنوان و چند لینک دارد (مثل «دسترسی سریع» یا «پشتیبانی»).
   */
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        icon: 'instagram' | 'telegram' | 'twitter' | 'youtube' | 'whatsapp';
        label?: string | null;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * متن انتهای فوتر؛ در صورت خالی ماندن از نام سایت استفاده می‌شود.
   */
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  general?:
    | T
    | {
        siteName?: T;
        logo?: T;
        supportPhone?: T;
        supportEmail?: T;
        timezone?: T;
      };
  booking?:
    | T
    | {
        slotStepMinutes?: T;
        cancellationWindowMinutes?: T;
        maxBookingHorizonDays?: T;
        defaultStatus?: T;
      };
  navigation?:
    | T
    | {
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
      };
  monetization?:
    | T
    | {
        enforceSubscription?: T;
        trialDays?: T;
      };
  auth?:
    | T
    | {
        registrationEnabled?: T;
        otpEnabled?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        image?: T;
      };
  stats?:
    | T
    | {
        barbersCount?: T;
        appointmentsCount?: T;
        citiesCount?: T;
        customersCount?: T;
      };
  whyUs?:
    | T
    | {
        title?: T;
        icon?: T;
        description?: T;
        id?: T;
      };
  popularServices?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  brand?:
    | T
    | {
        aboutText?: T;
      };
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  socialLinks?:
    | T
    | {
        icon?: T;
        label?: T;
        href?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}